import Head from 'next/head'
import Banner from '../components/Banner/Banner'
import Business from '../components/Business/Business'
import Footer from '../components/Footer/Footer'
import Navbar from '../components/Navbar/Navbar'
import Signup from '../components/Signup/Signup'
import Videos from '../components/Videos/Videos'

export default function Home() {
  return (
    <>
      <Head>
        <title>BharatPe Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Business />
      <Banner />
      <Videos />
      <Signup />
    </>
  )
}
